title: Blog
author: shincyan1900
subtitle: The life of a common man.
description: The blog of a common man.

url: "https://shincyan1900.github.io"
baseurl: "/blog"

footer_only_homepage: false
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Tags"
   link: "tags"
 - name: "Nikki"
   link: "nikki"
 - name: "Guestbook"
   link: "guestbook"
 - name: "RSS"
   absolute-link: "https://shincyan1900.github.io/blog/feed.xml"
# - name: "About"
#   link: "about"
# - name: "Resume"
#   absolute-link: "https://shincyan1900.github.io/CV.pdf"
